spring:
  config:
    import: optional:file:.env[.properties]

  # 로컬에 설치된 카프카를 사용하는 경우 대체
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: "PLAINTEXT"
    ssl:
      trust-store-location: ""
      trust-store-password: ""

management:
  tracing:
    sampling:
      probability: 1

topics:
  user:
    approved: dev-user-approved # 회원 승인
    deleted: dev-user-deleted # 회원 탈퇴

  store:
    updated: dev-store-updated # 업체 정보 수정됨

  hub:
    updated: dev-hub-updated # 허브 정보 수정됨