server:
  port: 13100

spring:
  application:
    name: config-server
  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/yonggyo1125/project-configs
          default-label: main
          search-paths:
            - configs/common
            - configs/{application}/{profile}
            - configs/{application}
          basedir: configs
          clone-on-start: true
