spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://keycloak.code-factory.co.kr/realms/spartahub"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/v1/hub/**
          filters:
            - 'RewritePath=/v1/hub/(?<path>.*), /\${path}'

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/user/**
          filters:
            - 'RewritePath=/v1/user/(?<path>.*), /\${path}'

        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/v1/store/**
          filters:
            - 'RewritePath=/v1/store/(?<path>.*), /\${path}'

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v1/product/**
          filters:
            - 'RewritePath=/v1/product/(?<path>.*), /\${path}'

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/v1/delivery/**
          filters:
            - 'RewritePath=/v1/delivery/(?<path>.*), /\${path}'

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: full
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /user-service/v3/api-docs
        name: USER API
      - url: /hub-service/v3/api-docs
        name: HUB API
      - url: /store-service/v3/api-docs
        name: STORE API
      - url: /product-service/v3/api-docs
        name: PRODUCT API
      - url: /delivery-service/v3/api-docs
        name: DELIVERY API